// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obmeooiwohwojfebylxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibWVvb2l3b2h3b2pmZWJ5bHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDk2ODksImV4cCI6MjA2NTc4NTY4OX0.udp-g8RB8iDIunWcRleEVD-ssLUmMhA0vR-eJH5aVZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);